### ISSUE TITLE
Fix doctests

### ISSUE THREAD

**Issue by Gankra** [contain-rs/lru-cache#1]
dashes vs underscores is causing trouble

**Comment by apasel422** [comment]
Presumably we need to add

``` rust
extern crate "lru-cache" as lru_cache;
```

to each one until Cargo handles the transformation for us.

**Comment by apasel422** [comment]
Of course, this will necessitate something like

``` rust
/// extern crate "lru-cache" as lru_cache;
/// fn main() {
/// // actual test code
/// }
```

**Comment by Gankra** [comment]
I'm pretty tempted to just let stuff keep failing at that cost. Anyway low priority while we handle all the other migrations.
